INSERT INTO neondb.public.tag (name) VALUES
                                         ('Popular'),
                                         ('Balanced'),
                                         ('Hidden gems'),
                                         ('Slow & easy'),
                                         ('Medium'),
                                         ('Fast-paced'),
                                         ('Culture'),
                                         ('Outdoors'),
                                         ('Relaxing'),
                                         ('Romantic'),
                                         ('Beaches'),
                                         ('Historic sites'),
                                         ('Museums'),
                                         ('Shopping'),
                                         ('Wildlife');
INSERT INTO neondb.public.activity (name,max_time,min_time) VALUES
                                                                ('sight seeing', '5:00:00','3:00:00'),
                                                                ('shopping', '5:00:00','3:00:00'),
                                                                ('eating', '5:00:00','3:00:00'),
                                                                ('drinking', '5:00:00','3:00:00'),
                                                                ('clubbing', '5:00:00','3:00:00'),
                                                                ('gambling', '5:00:00','3:00:00'),
                                                                ('relaxing', '5:00:00','3:00:00'),
                                                                ('golfing', '5:00:00','3:00:00'),
                                                                ('hiking', '5:00:00','3:00:00'),
                                                                ('swimming', '5:00:00','3:00:00'),
                                                                ('fishing', '5:00:00','3:00:00'),
                                                                ('boating', '5:00:00','3:00:00'),
                                                                ('skiing', '5:00:00','3:00:00'),
                                                                ('snowboarding', '5:00:00','3:00:00'),
                                                                ('snowmobiling', '5:00:00','3:00:00'),
                                                                ('hunting', '5:00:00','3:00:00'),
                                                                ('biking', '5:00:00','3:00:00'),
                                                                ('horseback riding', '5:00:00','3:00:00'),
                                                                ('rock climbing', '5:00:00','3:00:00'),
                                                                ('sky diving', '5:00:00','3:00:00'),
                                                                ('bungee jumping', '5:00:00','3:00:00'),
                                                                ('parasailing', '5:00:00','3:00:00'),
                                                                ('surfing', '5:00:00','3:00:00'),
                                                                ('scuba diving', '5:00:00','3:00:00'),
                                                                ('snorkeling', '5:00:00','3:00:00'),
                                                                ('kayaking', '5:00:00','3:00:00'),
                                                                ('canoeing', '5:00:00','3:00:00'),
                                                                ('rafting', '5:00:00','3:00:00'),
                                                                ('sailing', '5:00:00','3:00:00'),
                                                                ('whitewater rafting', '5:00:00','3:00:00'),
                                                                ('whitewater kayaking', '5:00:00','3:00:00'),
                                                                ('whitewater canoeing', '5:00:00','3:00:00');
-- Now, insert the data into the user table with varying picture sizes
INSERT INTO neondb.public.user (username, first_name, last_name, email, password, profile_pic, cover_pic) VALUES
                                                                                                              ('admin', 'admin', 'User', 'admin@example.com', 'password', 'https://picsum.photos/200', 'https://picsum.photos/200'),
                                                                                                              ('john_doe', 'John', 'Doe', 'john.doe@example.com', 'hashed_password', 'https://picsum.photos/250', 'https://picsum.photos/250'),
                                                                                                              ('jane_smith', 'Jane', 'Smith', 'jane.smith@example.com', 'hashed_password', 'https://picsum.photos/300', 'https://picsum.photos/300'),
                                                                                                              ('user1', 'User', 'One', 'user1@example.com', 'hashed_password', 'https://picsum.photos/350', 'https://picsum.photos/350'),
                                                                                                              ('user2', 'User', 'Two', 'user2@example.com', 'hashed_password', 'https://picsum.photos/400', 'https://picsum.photos/400'),
                                                                                                              ('alice', 'Alice', 'Johnson', 'alice@example.com', 'hashed_password', 'https://picsum.photos/450', 'https://picsum.photos/450'),
                                                                                                              ('bob', 'Bob', 'Smith', 'bob@example.com', 'hashed_password', 'https://picsum.photos/500', 'https://picsum.photos/500'),
                                                                                                              ('emma', 'Emma', 'Williams', 'emma@example.com', 'hashed_password', 'https://picsum.photos/200', 'https://picsum.photos/200'),
                                                                                                              ('michael', 'Michael', 'Brown', 'michael@example.com', 'hashed_password', 'https://picsum.photos/250', 'https://picsum.photos/250'),
                                                                                                              ('olivia', 'Olivia', 'Davis', 'olivia@example.com', 'hashed_password', 'https://picsum.photos/300', 'https://picsum.photos/300');
INSERT INTO  neondb.public.region( name) VALUES ('Coxs Bazar'),
                                                ('BandarBan'),
                                                ('Chattogram');
INSERT INTO  neondb.public.place_type(name) VALUES
                                                ('spot'),
                                                ('restaurant'),
                                                ('hotel');

INSERT INTO neondb.public.distance (first_place_id, second_place_id, journey_type, distance, estimated_time) VALUES
                                                                                                                 (3,4,'car',20.3,'0:30:00'),
                                                                                                                 (3,5,'car',20.3,'0:30:00'),
                                                                                                                 (3,6,'car',20.3,'0:30:00'),
                                                                                                                 (3,7,'car',20.3,'0:30:00'),
                                                                                                                 (3,8,'car',20.3,'0:30:00'),
                                                                                                                 (4,5,'car',20.3,'0:30:00'),
                                                                                                                 (4,6,'car',20.3,'0:30:00'),
                                                                                                                 (4,7,'car',20.3,'0:30:00'),
                                                                                                                 (4,8,'car',20.3,'0:30:00'),
                                                                                                                 (5,6,'car',20.3,'0:30:00'),
                                                                                                                 (5,7,'car',20.3,'0:30:00'),
                                                                                                                 (5,8,'car',20.3,'0:30:00'),
                                                                                                                 (6,7,'car',20.3,'0:30:00'),
                                                                                                                 (6,8,'car',20.3,'0:30:00'),
                                                                                                                 (7,8,'car',20.3,'0:30:00');
INSERT INTO neondb.public.spot_tag (place_id, tag_id) VALUES
                                                          (4,10),
                                                          (4,2),
                                                          (4,14),
                                                          (5,10),
                                                          (5,2),
                                                          (5,14),
                                                          (6,10),
                                                          (6,2),
                                                          (6,14),
                                                          (7,10),
                                                          (7,2),
                                                          (7,14),
                                                          (8,10),
                                                          (8,2),
                                                          (8,14);
INSERT INTO neondb.public.spot_activity(place_id, activity_id, tag_id, est_cost) VALUES
                                                                                     (4,40,10,300.0),
                                                                                     (4,41,11,300.0),
                                                                                     (4,42,12,300.0),
                                                                                     (5,43,13,300.0),
                                                                                     (5,44,14,300.0),
                                                                                     (5,45,15,300.0),
                                                                                     (6,46,3,300.0),
                                                                                     (6,47,4,300.0),
                                                                                     (6,48,5,300.0),
                                                                                     (7,49,6,300.0),
                                                                                     (7,50,7,300.0),
                                                                                     (7,51,9,300.0),
                                                                                     (8,52,12,300.0),
                                                                                     (8,53,14,300.0),
                                                                                     (8,54,1,300.0);
INSERT INTO neondb.public.event_detail(event_id, checked, note, generated_detail, expenditure) VALUES
                                                                                                   (1,true,'had so much fun.', ' This was a visit to some place',1000),
                                                                                                   (2,true,'had so much fun.', ' This was a visit to some place',1000),
                                                                                                   (3,true,'had so much fun.', ' This was a visit to some place',1000),
                                                                                                   (4,true,'had so much fun.', ' This was a visit to some place',1000),
                                                                                                   (5,true,'had so much fun.', ' This was a visit to some place',1000);
-- place id 14
-- 15
-- 16
-- 17
-- 18
-- 19
-- 20
-- 21
-- 22
-- 23
-- 24
-- 25
-- 26
-- 27
-- 29
-- 30
-- 31
-- 32
-- 33
-- est_cost is random value between 100 to 1000
INSERT INTO public.place_activity(place_id, activity_id, tag_id, est_cost) VALUES
                                                                               (14,1,1,200),
                                                                               (14,1,2,300),
                                                                               (14,1,3,350),
                                                                               (15,1,4,400),
                                                                               (15,1,5,500),
                                                                               (15,1,6,600),
                                                                               (16,1,7,700),
                                                                               (16,1,8,800),
                                                                               (16,1,9,900),
                                                                               (17,1,10,1000),
                                                                               (17,1,1,150),
                                                                               (17,1,2,250),
                                                                               (18,1,3,350),
                                                                               (18,1,4,450),
                                                                               (18,1,5,550),
                                                                               (19,1,6,650),
                                                                               (19,1,7,750),
                                                                               (19,1,8,850),
                                                                               (20,1,9,950),
                                                                               (20,1,10,50),
                                                                               (20,1,1,150),
                                                                               (21,1,2,250),
                                                                               (21,1,3,350),
                                                                               (21,1,4,250),
                                                                               (22,1,5,150),
                                                                               (22,1,6,50),
                                                                               (22,1,7,150),
                                                                               (23,1,8,250),
                                                                               (23,1,9,350),
                                                                               (23,1,10,450),
                                                                               (24,1,1,550),
                                                                               (24,1,2,650),
                                                                               (24,1,3,750),
                                                                               (25,1,4,850),
                                                                               (25,1,5,950),
                                                                               (25,1,6,50),
                                                                               (26,1,7,150),
                                                                               (26,1,8,250),
                                                                               (26,1,9,350),
                                                                               (27,1,10,450),
                                                                               (27,1,1,550),
                                                                               (27,1,2,650),
                                                                               (29,1,3,750),
                                                                               (29,1,4,850),
                                                                               (29,1,5,950),
                                                                               (30,1,6,50),
                                                                               (30,1,7,150),
                                                                               (30,1,8,250),
                                                                               (31,1,9,350),
                                                                               (31,1,10,450),
                                                                               (31,1,1,550),
                                                                               (32,1,2,650),
                                                                               (32,1,3,750),
                                                                               (32,1,4,850),
                                                                               (33,1,5,950),
                                                                               (33,1,6,50),
                                                                               (33,1,7,150),
                                                                               (14,2,8,450),
                                                                               (14,2,9,150),
                                                                               (14,2,10,350),
                                                                               (15,3,1,550),
                                                                               (15,3,2,650),
                                                                               (15,3,3,750),
                                                                               (16,4,4,850),
                                                                               (16,4,5,950),
                                                                               (16,4,6,50),
                                                                               (17,5,7,150),
                                                                               (17,5,8,250),
                                                                               (17,5,9,350),
                                                                               (18,6,10,450),
                                                                               (18,6,1,550),
                                                                               (18,6,2,650),
                                                                               (19,7,3,750),
                                                                               (19,7,4,850),
                                                                               (19,7,5,950),
                                                                               (20,8,6,50),
                                                                               (20,8,7,150),
                                                                               (20,8,8,250),
                                                                               (21,9,9,350),
                                                                               (21,9,10,450),
                                                                               (21,9,1,550),
                                                                               (22,10,2,650),
                                                                               (22,10,3,750),
                                                                               (22,10,4,850),
                                                                               (23,11,5,950),
                                                                               (23,11,6,50),
                                                                               (23,11,7,150),
                                                                               (24,12,8,250),
                                                                               (24,12,9,350),
                                                                               (24,12,10,450),
                                                                               (25,13,1,550),
                                                                               (25,13,2,650),
                                                                               (25,13,3,750),
                                                                               (26,14,4,850),
                                                                               (26,14,5,950),
                                                                               (26,14,6,50),
                                                                               (27,15,7,150),
                                                                               (27,15,8,250),
                                                                               (27,15,9,350),
                                                                               (29,3,3,750),
                                                                               (29,3,4,850),
                                                                               (29,3,5,950),
                                                                               (30,4,6,50),
                                                                               (30,4,7,150),
                                                                               (30,4,8,250),
                                                                               (31,5,9,350),
                                                                               (31,5,10,450),
                                                                               (31,5,1,550),
                                                                               (32,6,2,650),
                                                                               (32,6,3,750),
                                                                               (32,6,4,850),
                                                                               (33,7,5,950),
                                                                               (33,7,6,50),
                                                                               (33,7,7,150);
INSERT INTO mnb.public.place_activity (place_id, activity_id, tag_id, est_cost) VALUES
                                                                                    (64,1,1,100),
                                                                                    (64,1,2,100),
                                                                                    (64,1,3,100),
                                                                                    (65,1,4,100),
                                                                                    (65,1,5,100),
                                                                                    (65,1,6,100),
                                                                                    (66,1,7,100),
                                                                                    (66,1,8,100),
                                                                                    (66,1,9,100),
                                                                                    (67,1,10,100),
                                                                                    (67,1,1,100),
                                                                                    (67,1,2,100),
                                                                                    (68,1,3,100),
                                                                                    (68,1,4,100),
                                                                                    (68,1,5,100),
                                                                                    (69,1,6,100),
                                                                                    (69,1,7,100),
                                                                                    (69,1,8,100),
                                                                                    (70,1,9,100),
                                                                                    (70,1,10,100),
                                                                                    (70,1,1,100),
                                                                                    (71,1,2,100),
                                                                                    (71,1,3,100),
                                                                                    (71,1,4,100),
                                                                                    (72,1,5,100),
                                                                                    (72,1,6,100),
                                                                                    (72,1,7,100),
                                                                                    (73,1,8,100),
                                                                                    (73,1,9,100),
                                                                                    (73,1,10,100),
                                                                                    (64,2,1,100),
                                                                                    (64,2,2,100),
                                                                                    (64,2,3,100),
                                                                                    (65,3,4,100),
                                                                                    (65,3,5,100),
                                                                                    (65,3,6,100),
                                                                                    (66,4,7,100),
                                                                                    (66,4,8,100),
                                                                                    (66,4,9,100),
                                                                                    (67,5,10,100),
                                                                                    (67,5,1,100),
                                                                                    (67,5,2,100),
                                                                                    (68,6,3,100),
                                                                                    (68,6,4,100),
                                                                                    (68,6,5,100),
                                                                                    (69,7,6,100),
                                                                                    (69,7,7,100),
                                                                                    (69,7,8,100),
                                                                                    (70,8,9,100),
                                                                                    (70,8,10,100),
                                                                                    (70,8,1,100),
                                                                                    (71,9,2,100),
                                                                                    (71,9,3,100),
                                                                                    (71,9,4,100),
                                                                                    (72,10,5,100),
                                                                                    (72,10,6,100),
                                                                                    (72,10,7,100),
                                                                                    (73,11,8,100),
                                                                                    (73,11,9,100),
                                                                                    (73,11,10,100);